### ISSUE TITLE
Unable to open home page! TypeError: Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by roshisoftsol** [truffle-box/drizzle-box#15]
After minor tweaks in package.json file, 'npm run test' finally passed. (Refer to comments of #10)
But getting an error in Chrome console after doing npm run start. Got nothing in terminal though.

Error retrieving network ID:
TypeError: Cannot read property 'address' of undefined
    at http://localhost:3000/static/js/bundle.js:69576:103
From previous event:
    at new DrizzleContract (http://localhost:3000/static/js/bundle.js:69575:27)
    at Drizzle.getContracts (http://localhost:3000/static/js/bundle.js:69461:58)
    at http://localhost:3000/static/js/bundle.js:69442:17
    at <anonymous>

**Comment by sajclarke** [comment]
@roshisoftsol I fixed this error by switching to localhost:8545 on Metamask. If you changed the port you're running ganache on (e.g. 7545) then you can change metamask to run on that.

**Comment by pablog12** [comment]
I have that same error. I tried switching metamask to localhost:8545 and I still get the same error.

Could you please elaborate sajclarke? I can't seem to get this to work.

Thanks in advance.

**Comment by jkosior** [comment]
I have the same error, also tried switching metamask to localhost:8545. 

I have another error in Chrome Console:

Error initializing Drizzle.
Then the one from above.

How can I fix it?
Thanks in advance.

**Comment by moshebeeri** [comment]
Having the same issue
![image](https://user-images.githubusercontent.com/574405/39014466-21ca6cec-4423-11e8-98f8-f63a9ab74600.png)

**Comment by wangki** [comment]
I fixed this by deleting all the `.json` files under `build/contracts` and 
`
truffle compile
truffle migrate 
`

Again

**Comment by wangki** [comment]
Well, it seems it doesn't really fix the issue

**Comment by wangki** [comment]
https://github.com/truffle-box/drizzle-box/issues/18
"I had the same errors - fixed by changing my Metamask network to: localhost:8545 (the default Ganache port)"

**Comment by ColdDevil** [comment]
Okay, after 5 hours of trial&error, I found a solution. I guess it is an issue related to incompatible npm packages. This process works for me:
- open a terminal, start with an empty folder
- truffle unbox drizzle
- edit package.json and add to the dependencies section:
  - "eth-block-tracker-es5": "^2.3.2"
  - "web3": "1.0.0-beta.34"
- npm update (to install the aforementioned packages and to update drizzle and its components to the latest version)
- run in another terminal: ganache-cli -b 3
- truffle compile
- truffle migrate
- npm run start

**Comment by awrgold** [comment]
@ColdDevil this worked for me as well. Thanks for saving me hours of work!

**Comment by gdbjohnson** [comment]
@ColdDevil's solution worked for me too.

**Comment by briankostar** [comment]
@ColdDevil thanks, that actually did the trick
